"""E++ keyword aliases — many English ways to say the same thing."""

from __future__ import annotations

ALIASES: dict[str, str] = {
    "tell": "say",
    "speak": "say",
    "print": "say",
    "when": "if",
    "otherwise": "else",
    "done": "end",
    "finish": "end",
    "stop": "end",
    "let": "let",
    "make": "make",
    "set": "set",
    "be": "is",
    "are": "is",
    "ask": "ask",
    "question": "ask",
    "wait": "wait",
    "pause": "wait",
    "yes": "true",
    "no": "false",
    "while": "while",
    "until": "until",
    "for": "for",
    "each": "each",
    # "loop" kept for "break loop" — use "repeat" for loops
    "to": "to",
    "run": "run",
    "call": "run",
    "with": "with",
    "using": "with",
    "give": "give",
    "back": "back",
    "return": "give",
    "use": "use",
    "bring": "bring",
    "import": "import",
    "load": "use",
    "from": "from",
    "share": "share",
    "script": "script",
    "length": "length",
    "count": "length",
    "uppercase": "uppercase",
    "lowercase": "lowercase",
    "pick": "pick",
    "choose": "choose",
    "between": "between",
    "random": "random",
    "clear": "clear",
    "screen": "screen",
    "add": "add",
    "number": "number",
    "has": "has",
    "contains": "has",
    "of": "of",
    "in": "in",
    "item": "item",
    "first": "first",
    "last": "last",
    "the": "the",
    "second": "second",
    "seconds": "second",
    "minute": "minute",
    "minutes": "minute",
    # math (Lua math.*)
    "floor": "floor",
    "ceiling": "ceiling",
    "ceil": "ceiling",
    "round": "round",
    "absolute": "absolute",
    "abs": "absolute",
    "remainder": "remainder",
    "modulo": "remainder",
    "power": "power",
    "smallest": "smallest",
    "min": "smallest",
    "largest": "largest",
    "max": "largest",
    "square": "square",
    "root": "root",
    # text (Lua string.*)
    "slice": "slice",
    "find": "find",
    "replace": "replace",
    "split": "split",
    "join": "join",
    "trimmed": "trim",
    "trim": "trim",
    "starts": "starts",
    "ends": "ends",
    "copy": "copy",
    "repeated": "copy",
    # lists (Lua table.*)
    "remove": "remove",
    "sort": "sort",
    "reverse": "reverse",
    # control
    "break": "break",
    "exit": "break",
    "type": "type",
    "text": "text",
    "as": "as",
    # websites
    "start": "start",
    "website": "website",
    "save": "save",
    "open": "open",
    "heading": "heading",
    "paragraph": "paragraph",
    "button": "button",
    "link": "link",
    "input": "input",
    "picture": "picture",
    "background": "background",
    "font": "font",
    "page": "page",
    "goes": "goes",
    "that": "that",
    "color": "color",
    "divider": "divider",
    "line": "divider",
}

CANONICAL_KEYWORDS = {
    "is", "called", "say", "show", "if", "then", "else", "end", "repeat", "times",
    "plus", "minus", "divided", "by", "greater", "than", "less", "equal", "to", "not",
    "and", "or", "note", "let", "make", "set", "ask", "wait", "true", "false",
    "while", "until", "for", "each", "run", "with", "has", "of", "in", "item",
    "first", "last", "second", "minute", "the", "do", "keep", "going",
    "use", "bring", "import", "from", "share", "give", "back", "script",
    "length", "uppercase", "lowercase", "pick", "choose", "between", "random",
    "clear", "screen", "add", "number",
    "floor", "ceiling", "round", "absolute", "remainder", "power", "smallest", "largest",
    "square", "root", "slice", "find", "replace", "split", "join", "trim", "starts", "ends",
    "copy", "remove", "sort", "reverse", "break", "type", "text", "as", "loop",
    "start", "website", "save", "open", "heading", "paragraph", "button", "link", "input", "picture",
    "background", "font", "page", "goes", "that", "color", "divider", "line",
    *ALIASES.keys(),
}


def normalize_word(word: str) -> str:
    return ALIASES.get(word.lower(), word.lower())


def is_keyword(word: str) -> bool:
    return normalize_word(word) in CANONICAL_KEYWORDS
