"""E++ keyword aliases — many English ways to say the same thing."""

from __future__ import annotations

# Maps friendly / alternate words to one canonical keyword.
ALIASES: dict[str, str] = {
    # output
    "tell": "say",
    "speak": "say",
    "print": "say",
    "shout": "say",
    "yell": "say",
    # display value
    "display": "show",
    "write": "show",
    # conditions
    "when": "if",
    "otherwise": "else",
    "or else": "else",  # handled as two words: or + else -> else? skip
    # blocks
    "done": "end",
    "finish": "end",
    "stop": "end",
    # assignment helpers
    "let": "let",
    "make": "make",
    "set": "set",
    "be": "is",
    "are": "is",
    # input
    "ask": "ask",
    "question": "ask",
    # wait
    "wait": "wait",
    "pause": "wait",
    # booleans
    "yes": "true",
    "no": "false",
    # loops
    "while": "while",
    "until": "until",
    "for": "for",
    "each": "each",
    "loop": "repeat",
    # functions
    "to": "to",
    "run": "run",
    "call": "run",
    "with": "with",
    "using": "with",
    "give": "give",
    "back": "back",
    "return": "give",
    # modules
    "use": "use",
    "bring": "bring",
    "import": "import",
    "load": "use",
    "from": "from",
    "share": "share",
    "script": "script",
    # text & lists
    "length": "length",
    "uppercase": "uppercase",
    "lowercase": "lowercase",
    "pick": "pick",
    "choose": "choose",
    "between": "between",
    "random": "random",
    "clear": "clear",
    "screen": "screen",
    "add": "add",
    "number": "number",
    # data
    "has": "has",
    "contains": "has",
    # access
    "of": "of",
    "in": "in",
    "item": "item",
    "items": "item",
    "first": "first",
    "last": "last",
    # optional filler (skipped by parser)
    "the": "the",
    # time
    "second": "second",
    "seconds": "second",
    "minute": "minute",
    "minutes": "minute",
}

CANONICAL_KEYWORDS = {
    "is",
    "called",
    "say",
    "show",
    "if",
    "then",
    "else",
    "end",
    "repeat",
    "times",
    "plus",
    "minus",
    "divided",
    "by",
    "greater",
    "than",
    "less",
    "equal",
    "to",
    "not",
    "and",
    "or",
    "note",
    "let",
    "make",
    "set",
    "ask",
    "wait",
    "true",
    "false",
    "while",
    "until",
    "for",
    "each",
    "to",
    "run",
    "with",
    "has",
    "of",
    "in",
    "item",
    "first",
    "last",
    "second",
    "minute",
    "the",
    "do",
    "keep",
    "going",
    "use",
    "bring",
    "import",
    "from",
    "share",
    "give",
    "back",
    "script",
    "length",
    "uppercase",
    "lowercase",
    "pick",
    "choose",
    "between",
    "random",
    "clear",
    "screen",
    "add",
    "number",
    *ALIASES.keys(),
}


def normalize_word(word: str) -> str:
    lower = word.lower()
    return ALIASES.get(lower, lower)


def is_keyword(word: str) -> bool:
    return normalize_word(word) in CANONICAL_KEYWORDS or normalize_word(word) in {
        "is",
        "called",
        "say",
        "show",
        "if",
        "then",
        "else",
        "end",
        "repeat",
        "times",
        "plus",
        "minus",
        "divided",
        "by",
        "greater",
        "than",
        "less",
        "equal",
        "to",
        "not",
        "and",
        "or",
        "note",
        "let",
        "make",
        "set",
        "ask",
        "wait",
        "true",
        "false",
        "while",
        "until",
        "for",
        "each",
        "to",
        "run",
        "with",
        "has",
        "of",
        "in",
        "item",
        "first",
        "last",
        "second",
        "minute",
        "the",
        "do",
        "keep",
        "going",
        "use",
        "bring",
        "import",
        "from",
        "share",
        "give",
        "back",
        "script",
        "length",
        "uppercase",
        "lowercase",
        "pick",
        "choose",
        "between",
        "random",
        "clear",
        "screen",
        "add",
        "number",
    }
